title: "Sabneet Bains Portfolio"
description: "A portfolio site showcasing my projects and research."
theme: jekyll-theme-architect
markdown: kramdown
author:
  name: "Sabneet Bains"
  email: "sabneet.bains@outlook.com"
social:
  linkedin: "https://www.linkedin.com/in/sabneet-bains/"
  youtube: "https://www.youtube.com/@sabneetbains"
custom_css: "/assets/css/custom.css"
