# Site settings
title: Baleon
description: Baleon is a stylish and multifunctional theme for Jekyll
url: "https://yourusername.github.io"  # Replace with your GitHub Pages URL
baseurl: ""                           # Set this to your repository name if not using a user/organization site

# Build settings
markdown: kramdown
theme: minima                         # You can change or remove this if you use your custom theme
safe: true                           # GitHub Pages uses safe mode, so plugins must be approved

# Collections and includes
include:
  - assets                           # Ensure that the assets folder is processed

# Exclusions: Files or directories to ignore
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Plugins (only approved ones work on GitHub Pages)
plugins:
  - jekyll-feed

