title: "Sabneet Bains Portfolio"
description: "A comprehensive digital portfolio showcasing interdisciplinary research in computational physics, quantum computing, AI, machine learning, nonlinear dynamics, simulations, automation, reverse engineering, digital logic, game development, and data science."
url: "https://sabneet-bains.github.io"
baseurl: ""
author: "Sabneet Bains"
