title: "Your Name Portfolio"
description: "A digital portfolio showcasing my work, personality, and creative projects."
url: "https://yourusername.github.io"  # your GitHub Pages URL
baseurl: ""                           # set if you’re deploying to a subpath
author: "Your Name"
social:
  linkedin: "https://linkedin.com/in/yourprofile"
  github: "https://github.com/yourusername"
  youtube: "https://youtube.com/yourchannel"
